### PR TITLE
Update to crystal-db ~> 0.8.0

### PR DESCRIPTION
**Pull request by bcardiff**
There is a new release of crystal-db.

It would be ideal to release a crystal-pg 0.20.0 IMO

### CODE REVIEW

**Comment by bcardiff** [comment]
The failing CIs complain about

```
postgresql-10,11,12 : Depends: libicu55 (>= 55.1-1~) but it is not installable
                      Recommends: sysstat but it is not going to be installed
```

**Comment by will** [comment]
@bcardiff I think I figured out the CI problem, can you rebase please?

**Comment by bcardiff** [comment]
PR rebased!

**Comment by will** [comment]
Released `0.20.0` just now. Thanks :)

**Pull request merged**
