### PR TITLE
fix compatibility with Crystal 0.35.0

### PR DESCRIPTION
**Pull request by mamantoha**
related to https://github.com/crystal-lang/crystal/pull/8426

### CODE REVIEW

**Comment by bcardiff** [comment]
FYI there are a couple of more change to have compatibility in the upcoming Crystal 0.35 without warnings. I have them in https://github.com/will/crystal-pg/compare/master...bcardiff:crystal/0.35.0 . I think that would be all, although the release is not closed yet.

**Comment by mamantoha** [comment]
Hi @bcardiff. Nice. Then I close this PR.

**Comment by mamantoha** [comment]
Btw @bcardiff . Can you open PR as a draft? I checked PRs before opening this one. I didn't find any and decide to fix it myself. Thanks.

**Comment by bcardiff** [comment]
Done #206 :-) Sorry for keeping it for myself 🙈

**Pull request closed without merging**
