### PR TITLE
Add connection with using Hash values.

### PR DESCRIPTION
**Pull request by tebakane**
I'm sorry. I mistook and close PR.
https://github.com/will/crystal-pg/pull/25

Please discuss one more time about `Hash(YAML::Type, YAML::Type)` and `Hash(String, YAML:: Type)`.

Thanks.

### CODE REVIEW

**Comment by will** [comment]
Thanks for adding the spec.

That makes sense if Crystal's YAML parser returns `YAML::Type`=>`YAML::Type`. However, I wonder though if we can instead go to just `initialize(parameters : Hash)` and let the compiler make sure that both sides of the hash have `#to_s` defined.

**Comment by jhass** [comment]
That was what @tebakane tried initially and I was suggesting `String|Symbol => String|Int`. If we want to be open it should be just `Hash` indeed.

**Comment by will** [comment]
Yeah, I see where that came from, but I think this works. I've merged this in and went ahead made that change. 

Thanks!

**Comment by tebakane** [comment]
Thanks.

**Pull request merged**
