### PR TITLE
Add escape_literal overload for binary data.

### PR DESCRIPTION
**Pull request by technorama**
Add spec for escape_literal.
Fix compiler/syntax error.

### CODE REVIEW

**Comment by jhass** [comment]
Shouldn't it add an `E` in front? http://www.postgresql.org/docs/9.4/static/datatype-binary.html

**Comment by technorama** [comment]
I don't believe so.  Escaped quoting is optional.

From the document you referenced:
> In some contexts, the initial backslash may need to be escaped by doubling it, in the same cases in which backslashes have to be doubled in escape format; 

> The reason multiple backslashes are required, as shown in Table 8-7, is that an input string written as a string literal must pass through two parse phases in the PostgreSQL server. The first backslash of each pair is interpreted as an escape character by the string-literal parser (assuming escape string syntax is used) and is therefore consumed, leaving the second backslash of the pair.

**Comment by technorama** [comment]
@will Binary data is corrupted without this PR.  Crystal-pg doesn't even compile without the space before the colon.

**Comment by will** [comment]
Thanks for the reminder. Interesting that the colon thing didn't break the specs though.

**Comment by jhass** [comment]
It'll break with the next Crystal release, 0.8 is still fine with it.

**Comment by technorama** [comment]
That must be why it didn't compile for me.  I'm using HEAD.

**Pull request merged**
