### PR TITLE
(incomplete) compile on 0.18.0

### PR DESCRIPTION
**Pull request by will**
Still openssl spec failures though

### CODE REVIEW

**Comment by jhass** [comment]
Mmh, which specs?

**Comment by will** [comment]
There is a file you need to touch to enable some of the auth specs. They're
not on by default because they need some setup on your local Postgres
server that isn't standard with brew/apt/etc

**Comment by jhass** [comment]
Yup found that, they pass for me.

**Comment by will** [comment]
`SSL_connect: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed (OpenSSL::SSL::Error)`

I'm just using a self-signed cert, I think the default verification level went up in this release.

**Comment by jhass** [comment]
Yes it did, I guess it works for me because I didn't explicitly configure my postgres to enable TLS. You should get a way with abusing your self signed cert as a CA certificate too:
```cr
context = OpenSSL::SSL::Context::Client.new
context.ca_certificates = ENV["POSTGRESQL_SERVER_CERTIFICATE"]
socket  = OpenSSL::SSL:Socket::Client.new(socket, context: context, hostname: host)
```
Of course proper setups should either use their own proper CA cert here and create their PostgreSQL server certificate from it, or use some blessed PKIX.

**Comment by will** [comment]
libpq supports a few different levels https://www.postgresql.org/docs/current/static/libpq-ssl.html table 31-1

**Comment by jhass** [comment]
* `disable`: Don't create a `OpenSSL::SSL:Socket::Client` at all. Probably refuse connection if the server demands it.
* `allow`: Application protocol specific, don't request from the client, but create a `OpenSSL::SSL::Socket::Client` in `require` mode.
* `prefer`: Application protocol specific, request from the client, create a `OpenSSL::SSL::Socket::Client` in `require` mode if the server supports it.
* `require`, create a `OpenSSL::SSL::Socket::Client`, pass a context with `verify_mode` set to `OpenSSL::SSL::VerifyMode::NONE`, the `hostname` parameter of the socket should get ignored.
* `verify-ca`: create a standard `OpenSSL::SSL::Socket::Client` with no additional options, do not pass the `hostname` parameter.
* `verify-full`: create a standard `OpenSSL::SSL::Socket::Client` with the `hostname` parameter.

That is if you would want to mirror what libpq does, I'm not sure I would recommend that. Allowing the client to pass a `OpenSSL::SSL::Context::Client` might be easier and a bit more flexible, it's what `HTTP::Client` does.

**Pull request merged**
